import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import './globals.css'
import DashboardGuard from '@/components/guard/dashboardGuard'
import PublicGuard from '@/components/guard/publicGuard'
import { Toaster } from '@/components/ui/sonner'
import { AuthBootstrap } from '@/providers/authBoothStrap'
import { QueryProvider } from '@/providers/queryProvider'
import { ThemeProvider } from '@/providers/themeProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'CMS Admin Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>
            <AuthBootstrap>
              <PublicGuard>
              <DashboardGuard>{children}</DashboardGuard>
              </PublicGuard>
            </AuthBootstrap>
            <Toaster position={'top-center'} richColors />
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
